FROM node:14-alpine

WORKDIR '/app'

COPY package.json .
RUN npm install
COPY . .

CMD ["npm", "run", "start"]

# make sure to specific the file when use docker build "docker build -f Dockerfile.dev ."